on:
  workflow_dispatch:
    inputs:
      releaseFilePath:
        description: 'Define the path of RELEASE file'
        required: true
        default: 'RELEASE'
        options:
          - 'RELEASE'
          - 'testdata/RELEASE'
      newTag:
        description: 'new tag'
        required: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dionomusuko/gh-release-with-wf-dispatch@master
        with:
          "github_token": ${{ secrets.GITHUB_TOKEN }}
          "owner": ${{ github.event.repository.owner.login }}
          "repo": ${{ github.event.repository.full_name }}
          "release_file_path": ${{ github.event.inputs.releaeFilePath }}
          "base_branch": ${{ github.event.repository.default_branch }}
          "new_tag": ${{ github.event.inputs.newTag }}
